name: Build and Deploy the Web Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build the Docker Image
        run: docker build -t web_application .

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Tag the Docker Image
        run: docker tag web_application ${{ secrets.DOCKER_HUB_USERNAME }}/web_application

      - name: Push the Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/web_application
